### ISSUE TITLE
Cut config files into hosts conf file and rooms conf file

### ISSUE THREAD

**Issue by arthur91f** [arthur91f/exeiac#148]
Stay in the confi file
```yaml
modules:
  - name: execute-readme
    path: /home/arthur91f/git/exeiac-test/exeiac-modules/execute-readme.sh
  - name: terraform
    path: /home/arthur91f/git/exeiac-test/exeiac-modules/terraform.sh
rooms:
  - name: environment
    path: /home/arthur91f/git/exeiac-test/environment
  - name: wordpress-service
    path: /home/arthur91f/git/exeiac-test/wordpress-service
default_arguments:
  other_options: []
```

Have to be in rooms config file, not in host config_file
```yaml
default_arguments:
  other_options: []
  inputs_needed_for:
    - plan
    - lay
    - remove
  default_is_input_needed: false
```
